/* static.c - autogenerated by makefile */
#include <re_types.h>
#include <re_mod.h>

// extern const struct mod_export exports_debug_cmd;
extern const struct mod_export exports_jdkcodec;
extern const struct mod_export exports_g711;
extern const struct mod_export exports_androidgles;
// extern const struct mod_export exports_stdio;
extern const struct mod_export exports_syslog;
extern const struct mod_export exports_fakevideo;
//extern const struct mod_export exports_vidsrc_cb;
//extern const struct mod_export exports_avcodec;
extern const struct mod_export exports_opensles;
//extern const struct mod_export exports_dtls_srtp;
//extern const struct mod_export exports_echo;
//extern const struct mod_export exports_aubridge;
//extern const struct mod_export exports_stun;
//extern const struct mod_export exports_turn;
//extern const struct mod_export exports_ice;
//extern const struct mod_export exports_natbd;
//extern const struct mod_export exports_auloop;
//extern const struct mod_export exports_presence;
extern const struct mod_export exports_menu;
extern const struct mod_export exports_contact;
//extern const struct mod_export exports_vumeter;
//extern const struct mod_export exports_mwi;
extern const struct mod_export exports_account;
//extern const struct mod_export exports_natpmp;
//extern const struct mod_export exports_httpd;
//extern const struct mod_export exports_srtp;
extern const struct mod_export exports_uuid;
//extern const struct mod_export exports_debug_cmd;
//extern const struct mod_export exports_aubridge;
//extern const struct mod_export exports_aufile;
//extern const struct mod_export exports_vidloop;
//extern const struct mod_export exports_selfview;
//extern const struct mod_export exports_vidbridge;
//extern const struct mod_export exports_dtls_srtp;

const struct mod_export *mod_table[] = {
  // &exports_debug_cmd,
  &exports_jdkcodec,
  &exports_g711,
 &exports_androidgles,
  // &exports_stdio,
  &exports_syslog,
  &exports_fakevideo,
// &exports_vidsrc_cb,
//  &exports_avcodec,
  &exports_opensles,
//  &exports_dtls_srtp,
//  &exports_echo,
//  &exports_aubridge,
//  &exports_stun,
//  &exports_turn,
//  &exports_ice,
//  &exports_natbd,
//  &exports_auloop,
//  &exports_presence,
  &exports_menu,
  &exports_contact,
//  &exports_vumeter,
//  &exports_mwi,
  &exports_account,
//  &exports_natpmp,
//  &exports_httpd,
//  &exports_srtp,
  &exports_uuid,
//  &exports_debug_cmd,
//  &exports_aubridge,
//  &exports_aufile,
// &exports_vidloop,
//  &exports_selfview,
//  &exports_vidbridge,
//  &exports_dtls_srtp,
  NULL
};
